export const type = {
    FETCH_ITEMS_REQUEST: 'FETCH_ITEMS_REQUEST',
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
    
    FETCH_ITEM_DETAIL_REQUEST: 'FETCH_ITEM_DETAIL_REQUEST',
    FETCH_ITEM_DETAIL_SUCCESS: 'FETCH_ITEM_DETAIL_SUCCESS',
    FETCH_ITEM_DETAIL_FAILURE: 'FETCH_ITEM_DETAIL_FAILURE',
    
    CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
    DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
  };
  